"""add portfolio tables

Revision ID: 33c6419acfc6
Revises: 9083615fef0b
Create Date: 2026-04-16 22:48:21.537743

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import fastapi_users_db_sqlalchemy


# revision identifiers, used by Alembic.
revision: str = '33c6419acfc6'
down_revision: Union[str, Sequence[str], None] = '9083615fef0b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('diagram_questions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', fastapi_users_db_sqlalchemy.generics.GUID(), nullable=False),
    sa.Column('diagram_type', sa.String(length=48), nullable=False),
    sa.Column('criterias', sa.String(length=64), nullable=False),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.String(length=48), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_diagram_questions_external_id'), 'diagram_questions', ['external_id'], unique=False)
    op.create_index(op.f('ix_diagram_questions_user_id'), 'diagram_questions', ['user_id'], unique=False)
    op.create_table('investment_targets',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', fastapi_users_db_sqlalchemy.generics.GUID(), nullable=False),
    sa.Column('asset_type', sa.String(length=48), nullable=False),
    sa.Column('target_percentage', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'asset_type', name='uq_target_user_type')
    )
    op.create_index(op.f('ix_investment_targets_user_id'), 'investment_targets', ['user_id'], unique=False)
    op.create_table('positions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', fastapi_users_db_sqlalchemy.generics.GUID(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('asset_type', sa.String(length=48), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('current_price', sa.Float(), nullable=True),
    sa.Column('strength', sa.Integer(), nullable=False),
    sa.Column('diagram_responses', sa.JSON(), nullable=True),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_positions_asset_type'), 'positions', ['asset_type'], unique=False)
    op.create_index(op.f('ix_positions_user_id'), 'positions', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_positions_user_id'), table_name='positions')
    op.drop_index(op.f('ix_positions_asset_type'), table_name='positions')
    op.drop_table('positions')
    op.drop_index(op.f('ix_investment_targets_user_id'), table_name='investment_targets')
    op.drop_table('investment_targets')
    op.drop_index(op.f('ix_diagram_questions_user_id'), table_name='diagram_questions')
    op.drop_index(op.f('ix_diagram_questions_external_id'), table_name='diagram_questions')
    op.drop_table('diagram_questions')
    # ### end Alembic commands ###
