"""add aporte tables

Revision ID: 7aa25fec512c
Revises: 33c6419acfc6
Create Date: 2026-04-17 03:05:11.540054

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import fastapi_users_db_sqlalchemy


# revision identifiers, used by Alembic.
revision: str = '7aa25fec512c'
down_revision: Union[str, Sequence[str], None] = '33c6419acfc6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aporte_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', fastapi_users_db_sqlalchemy.generics.GUID(), nullable=False),
    sa.Column('aporte_value_brl', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_aporte_events_user_id'), 'aporte_events', ['user_id'], unique=False)
    op.create_table('aporte_allocations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('aporte_event_id', sa.Uuid(), nullable=False),
    sa.Column('position_id', sa.Uuid(), nullable=True),
    sa.Column('position_name_snapshot', sa.String(length=128), nullable=False),
    sa.Column('asset_type_snapshot', sa.String(length=48), nullable=False),
    sa.Column('price_at_aporte_brl', sa.Float(), nullable=True),
    sa.Column('suggested_value_brl', sa.Float(), nullable=False),
    sa.Column('suggested_quantity', sa.Float(), nullable=False),
    sa.Column('applied', sa.Boolean(), nullable=False),
    sa.Column('applied_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('applied_value_brl', sa.Float(), nullable=True),
    sa.Column('applied_quantity', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['aporte_event_id'], ['aporte_events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['position_id'], ['positions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_aporte_allocations_aporte_event_id'), 'aporte_allocations', ['aporte_event_id'], unique=False)
    op.create_index(op.f('ix_aporte_allocations_position_id'), 'aporte_allocations', ['position_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_aporte_allocations_position_id'), table_name='aporte_allocations')
    op.drop_index(op.f('ix_aporte_allocations_aporte_event_id'), table_name='aporte_allocations')
    op.drop_table('aporte_allocations')
    op.drop_index(op.f('ix_aporte_events_user_id'), table_name='aporte_events')
    op.drop_table('aporte_events')
    # ### end Alembic commands ###
